services:
  - type: web
    name: site-fastapi
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: EMAIL_ORIGEM
        value: seuemail@gmail.com
      - key: EMAIL_DESTINO
        value: destinatario@gmail.com
      - key: SENHA_APP
        value: sua_senha_de_app